'use client'

import { useState } from 'react'
import { ArrowUpRight, Check, Download, GitBranch, Link, Mail, Menu, Phone, X } from 'lucide-react'

const contact = { email: 'a.mohamed.elewaisy@gmail.com', phone: '+201018721622', linkedin: 'https://www.linkedin.com/in/ahmed-mohamed-98266a2a9/', github: 'https://github.com/ahmed55mo' }
const projects = [
  { title: 'AI-Based RPG Game', category: 'Generative AI · LLMs · RAG · Multi-Agent Systems', description: 'An AI-driven RPG game that uses Generative AI to create dynamic NPC dialogue and storytelling, combining local LLMs, RAG, and multi-agent orchestration.', tags: ['Python', 'Ollama', 'Phi-3 Mini', 'LangChain', 'LangGraph', 'FastAPI', 'RAG'], github: 'http://github.com/abdallahkareem/Lost-Kingdom-AI-RPG', featured: true, visual: 'rag' },
  { title: 'Bender Gestalt Analysis', category: 'Computer Vision · Deep Learning · Image Analysis', description: 'An automated drawing-analysis system comparing student drawings with reference templates using image processing, geometric similarity measures, and visual feature analysis.', tags: ['Python', 'OpenCV', 'scikit-image', 'HU Moments', 'Hausdorff Distance'], github: 'https://github.com/abdallahkareem/bender-gestalt-analysis', visual: 'vision' },
  { title: 'Fake News Detection', category: 'NLP · Deep Learning · Text Classification', description: 'An NLP text-classification project for detecting fake news using CNN, LSTM, BiLSTM, BERT, and DistilBERT models with GloVe embeddings.', tags: ['Python', 'TensorFlow', 'PyTorch', 'Hugging Face', 'GloVe', 'Keras', 'Scikit-learn'], github: 'https://github.com/ahmed55mo/fake-news-detection', visual: 'text' },
  { title: 'Image Filters & Processing', category: 'Image Processing · C++', description: 'A C++ image-processing application implementing image filtering and processing operations with reusable algorithms.', tags: ['C++', 'Image Processing', 'Algorithms'], github: 'https://github.com/ahmed55mo/Image-Filters-Processing', visual: 'code' },
  { title: 'Arcadia Engine', category: 'Game Engine · C++ · OOP', description: 'A terminal-based game engine simulator containing multiple games and a computer opponent system for AI-controlled play where supported.', tags: ['C++', 'OOP', 'Algorithms', 'Game Architecture'], github: 'https://github.com/ahmed55mo/Arcadia_Engine', visual: 'board' },
]
const skills = { Programming: ['Python', 'C++'], 'Machine Learning': ['Machine Learning', 'Supervised Learning', 'Unsupervised Learning', 'Feature Engineering', 'Hyperparameter Tuning'], 'Deep Learning': ['Neural Networks', 'CNNs', 'RNNs', 'LSTMs', 'Transformers', 'Transfer Learning'], NLP: ['NLP', 'Text Classification', 'Semantic Search', 'Transformers', 'Arabic NLP'], 'Generative AI': ['LLMs', 'RAG', 'Prompt Engineering', 'Embeddings', 'Vector Databases', 'Agentic AI'], 'Frameworks / Libraries': ['TensorFlow', 'PyTorch', 'Scikit-learn', 'Keras', 'OpenCV', 'Pandas', 'NumPy', 'Matplotlib', 'LangChain', 'LangGraph', 'Hugging Face Transformers'], Tools: ['Git', 'GitHub', 'Jupyter Notebook', 'Google Colab', 'VS Code', 'Ollama', 'FastAPI'] }

function SectionHeading({ number, eyebrow, title, copy }: { number: string; eyebrow: string; title: string; copy?: string }) { return <div className="section-heading reveal"><div className="section-index">{number} <span /></div><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2>{copy && <p className="section-copy">{copy}</p>}</div></div> }
function ProjectVisual({ type }: { type: string }) { if (type === 'rag') return <div className="visual-rag"><div className="rag-stack"><span>LOCAL LLM</span><span>RAG</span><span>AGENTS</span></div><div className="visual-arrow">→</div><div className="rag-core"><span>RPG</span><small>story engine</small></div><div className="visual-answer">NPC dialogue<span>▰ ▰ ▰</span></div></div>; if (type === 'vision') return <div className="visual-vision"><div className="draw-box"><span className="sketch-circle" /><span className="sketch-line" /></div><div className="versus">VS</div><div className="draw-box alt"><span className="sketch-circle" /><span className="sketch-line" /></div><div className="similarity">geometric analysis <b>HU / H</b></div></div>; if (type === 'text') return <div className="visual-flow"><span>“Is this story<br />fact or fiction?”</span><i>↓</i><strong>classified</strong><em>CNN · BERT · LSTM</em></div>; if (type === 'code') return <div className="code-visual"><span>01</span><span>filter(image) {'{'}</span><span className="indent">return process(pixels)</span><span>{'}'}</span><b>● ● ●</b></div>; return <div className="board-visual">{Array.from({ length: 16 }, (_, i) => <span key={i} className={i % 5 === 0 ? 'piece' : ''} />)}</div> }

export default function Page() {
  const [menuOpen, setMenuOpen] = useState(false); const [filter, setFilter] = useState('All'); const filters = ['All', 'Generative AI', 'Computer Vision', 'NLP', 'C++']; const visibleProjects = filter === 'All' ? projects : projects.filter(p => p.category.toLowerCase().includes(filter.toLowerCase()))
  return <main>
    <nav className="nav"><a className="brand" href="#home">AM<span>.</span></a><div className={`nav-links ${menuOpen ? 'open' : ''}`}>{['About', 'Projects', 'Skills', 'Experience', 'Contact'].map(item => <a href={`#${item.toLowerCase()}`} key={item} onClick={() => setMenuOpen(false)}>{item}</a>)}<a className="nav-cta" href={`mailto:${contact.email}`}>Let&apos;s Talk <ArrowUpRight size={15} /></a></div><button className="menu-button" aria-label={menuOpen ? 'Close menu' : 'Open menu'} onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X /> : <Menu />}</button></nav>
    <section id="home" className="hero page-pad"><div className="hero-copy reveal"><p className="eyebrow"><span className="status-dot" /> Available for AI / ML projects</p><p className="hero-label">GENERATIVE AI <span>·</span> AGENTIC AI <span>·</span> MACHINE LEARNING</p><h1>Building intelligent<br /><span>systems with AI.</span></h1><p className="hero-text">I am Ahmed Mohamed, a Generative and Agentic AI Engineer building practical applications with LLMs, RAG, NLP, Machine Learning, and Deep Learning.</p><div className="hero-actions"><a className="button primary" href="#projects">View my work <ArrowUpRight size={17} /></a><a className="button secondary" href="/Ahmed_Mohamed_AI_Engineer.pdf" download><Download size={16} /> Download CV</a><a className="button secondary" href={`mailto:${contact.email}`}>Let&apos;s work together <ArrowUpRight size={17} /></a></div></div><div className="hero-visual reveal"><div className="visual-label">SYSTEM / RETRIEVAL PIPELINE <span>01</span></div><div className="hero-portrait-wrap"><img className="hero-portrait" src="https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ChatGPT%20edited%20profile%20image-e9NC5kKzZBqiHGbrw3oZqUcvVHKUdj.png" alt="Ahmed Mohamed - AI Engineer" /></div><div className="visual-footer"><span>prompt → context → response</span><span className="pulse-line" /></div></div></section>
    <div className="tech-strip"><span className="strip-label">Technologies I work with</span>{['Python', 'PyTorch', 'TensorFlow', 'LangChain', 'LangGraph', 'Hugging Face', 'Ollama', 'FastAPI'].map(x => <span key={x}>{x}</span>)}</div>
    <section id="about" className="section page-pad about"><SectionHeading number="01" eyebrow="The person behind the systems" title="Turning AI concepts into working systems." copy="I am an emerging AI Engineer focused on Generative AI and Agentic AI. My hands-on work spans LLMs, RAG, NLP, Machine Learning, and Deep Learning, grounded in practical projects and internship experience." /><div className="about-grid"><div className="about-statement"><span>GENERATIVE / AGENTIC AI</span><p>“The most useful AI is the kind that fits naturally into the problem it is solving.”</p></div><div className="about-points"><div><b>01</b><span>Build with intent</span><p>Start with the real problem, not the most fashionable model.</p></div><div><b>02</b><span>Stay curious</span><p>Experiment across language, vision, data, and intelligent agents.</p></div></div></div></section>
    <section id="projects" className="section page-pad projects"><SectionHeading number="02" eyebrow="Selected work" title="Proof through projects." copy="Generative AI, computer vision, NLP, and C++ systems built through study, experimentation, and practice." /><div className="filters">{filters.map(x => <button className={filter === x ? 'active' : ''} onClick={() => setFilter(x)} key={x}>{x}</button>)}</div><div className="project-grid">{visibleProjects.map((p, i) => <article className={`project-card ${p.featured ? 'featured' : ''}`} key={p.title}><div className="project-top"><span>0{i + 1}</span><span>{p.category}</span></div><ProjectVisual type={p.visual} /><div className="project-info"><h3>{p.title}</h3><p>{p.description}</p><div className="tags">{p.tags.map(tag => <span key={tag}>{tag}</span>)}</div><a href={p.github} target="_blank" rel="noopener noreferrer" className="project-link">View on GitHub <GitBranch size={15} /><ArrowUpRight size={14} /></a></div></article>)}</div></section>
    <section className="section page-pad capabilities"><SectionHeading number="03" eyebrow="Capabilities" title="What I build." /><div className="cap-grid">{[['01', '⌁', 'LLM Applications', 'Applications around language models, prompting, context, and inference workflows.'], ['02', '⌬', 'RAG Systems', 'Retrieval pipelines connecting LLMs with external knowledge and documents.'], ['03', '◌', 'NLP Solutions', 'Text processing, classification, semantic search, embeddings, and language understanding.'], ['04', '⌘', 'Agentic AI', 'Multi-agent workflows that turn models into useful, orchestrated systems.']].map(([n, icon, title, text]) => <div className="cap-card" key={title}><span className="cap-number">{n}</span><i>{icon}</i><h3>{title}</h3><p>{text}</p><ArrowUpRight className="cap-arrow" size={18} /></div>)}</div></section>
    <section id="skills" className="section page-pad skills"><SectionHeading number="04" eyebrow="Technical toolkit" title="Skills with a purpose." copy="A practical toolkit for taking an idea from raw data to a working intelligent system." /><div className="skills-grid">{Object.entries(skills).map(([group, items]) => <div className="skill-group" key={group}><h3>{group}</h3><div>{items.map(skill => <span key={skill}><Check size={13} />{skill}</span>)}</div></div>)}</div></section>
    <section className="section page-pad process"><SectionHeading number="05" eyebrow="Engineering process" title="How I approach AI problems." /><div className="process-grid">{[['01', 'Understand', 'Define the actual problem and desired outcome.'], ['02', 'Prepare', 'Collect, clean, structure, and understand the data.'], ['03', 'Build', 'Develop the appropriate ML, NLP, LLM, or RAG solution.'], ['04', 'Evaluate', 'Measure quality, reliability, and usefulness.'], ['05', 'Improve', 'Iterate based on results and real-world requirements.']].map(([n, title, text]) => <div className="process-step" key={title}><span>{n}</span><div><h3>{title}</h3><p>{text}</p></div></div>)}</div></section>
    <section id="experience" className="section page-pad experience"><SectionHeading number="06" eyebrow="Background" title="Built through study and practice." /><div className="timeline"><div className="timeline-item"><span className="timeline-dot" /><p className="timeline-date">EDUCATION · EXPECTED 2027</p><h3>B.Sc. in Computer Science</h3><p>Faculty of Computers and Artificial Intelligence, Cairo University<br />Major: Artificial Intelligence</p></div><div className="timeline-item"><span className="timeline-dot" /><p className="timeline-date">07/2026 – 08/2026 · NATIONAL TELECOMMUNICATION INSTITUTE</p><h3>NLP Engineer Intern</h3><p>NLP pipelines, preprocessing, EDA, multi-class classification, Arabic text processing, Transformer models, Hugging Face, RAG, LangChain, LangGraph, REST APIs, Generative AI, and Agentic AI.</p></div></div></section>
    <section className="section page-pad code-section"><div className="code-copy"><p className="eyebrow">Built in code</p><h2>Ideas become real<br /><span>when they run.</span></h2><p>I believe AI engineering is demonstrated through working systems, experiments, and code.</p><a className="button secondary" href={contact.github} target="_blank" rel="noopener noreferrer"><GitBranch size={16} /> View GitHub <ArrowUpRight size={17} /></a></div><div className="code-grid" aria-hidden="true">{Array.from({ length: 100 }, (_, i) => <i key={i} style={{ opacity: `${0.15 + ((i * 7) % 70) / 100}` }} />)}</div></section>
    <section id="contact" className="contact page-pad"><p className="eyebrow">07 / Contact</p><h2>Have an AI problem<br /><span>to solve?</span></h2><p>Let&apos;s turn your idea into a practical AI solution.</p><div className="contact-actions"><a className="button primary" href={`mailto:${contact.email}`}>Send Me an Email <Mail size={17} /></a><a className="button secondary" href={contact.linkedin} target="_blank" rel="noopener noreferrer"><Link size={16} /> Connect on LinkedIn</a><a className="button secondary" href={contact.github} target="_blank" rel="noopener noreferrer"><GitBranch size={16} /> View GitHub</a></div><div className="contact-links"><a href={`mailto:${contact.email}`}><Mail size={13} /> EMAIL / <b>{contact.email}</b></a><a href={contact.linkedin} target="_blank" rel="noopener noreferrer"><Link size={13} /> LINKEDIN / <b>ahmed-mohamed-98266a2a9</b></a><a href={contact.github} target="_blank" rel="noopener noreferrer"><GitBranch size={13} /> GITHUB / <b>ahmed55mo</b></a><a href={`tel:${contact.phone}`}><Phone size={13} /> PHONE / <b>{contact.phone}</b></a></div></section>
    <footer><span className="brand">AM<span>.</span></span><span>Generative and Agentic AI Engineer · © 2026 Ahmed Mohamed</span><div><a href={contact.linkedin} target="_blank" rel="noopener noreferrer"><Link size={14} /></a><a href={contact.github} target="_blank" rel="noopener noreferrer"><GitBranch size={14} /></a></div></footer>
  </main>
}
